export const ActionTypes = {
	BOOK_SELECTED: 'BOOK_SELECTED',
	PASSWORD_CHANGED: 'PASSWORD_CHANGED',
	LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
	LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
	LOGIN_USER: 'LOGIN_USER'
};
